/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function getPfpPath(uuid: string) {
    return invoke()<string>("get_pfp_path", { uuid })
}

/**
 * get the users.json
 */
export function getUsers() {
    return invoke()<UsersJson>("get_users")
}

export function changeActiveUser(uuid: string) {
    return invoke()<null>("change_active_user", { uuid })
}

export function logoutUser(uuid: string) {
    return invoke()<null>("logout_user", { uuid })
}

export type UsersJson = { active: string | null; users: { [key: string]: NexusUser } }
export type NexusUser = { uuid: string; username: string; access_token: string; refresh_token: string; expires: string }
